"""Resolution: two chains into one `RuleSet`, and the generated artefacts.

Spec 4.4. Chain 1 is configuration — hub `taller.yml`, then the profile, then the
project's `taller.yml`, by deep merge. Chain 2 is slice text — hub modules in
profile order, then the project's `constitution/`, with its `never.md` appended.
They are separate on purpose: **nothing in `constitution/` sets configuration**,
and prose is **only ever appended**, so a project cannot delete a hub prohibition.
The only way a rule stops applying is an override with a reason (spec 4.5).

`resolve()` writes nothing and calls nothing over the network. That purity is
what makes spec 4.6's byte-for-byte tamper check possible: a `resolve()` that
wrote the snapshot would rewrite the very file the check compares, so the check
could never fail. The renderers serialise; only `gitio.commit_to_main()` writes.
"""

from __future__ import annotations

import json
import math
import re
from datetime import date, datetime
from pathlib import Path
from typing import Any

import yaml

from . import catalogue, config, overrides, paths, registry
from .errors import ConfigError

RuleSet = dict[str, Any]
ResolvedSlice = dict[str, Any]

# Spec 4.3. Exactly nine, in reading order; the list is closed.
SLICE_NAMES: tuple[str, ...] = (
    "product", "architecture", "stack", "conventions", "security", "ux",
    "brand", "never", "overrides",
)

# Spec 4.3: what makes a project itself. A hub module of one of these names is
# ignored - not merged, not preferred.
PROJECT_ONLY_SLICES = frozenset({"product", "architecture", "overrides"})

# Profile keys that are not configuration and must not reach chain 1. `brand` is
# a slug the registry records per project, not a config value (spec 4.1).
PROFILE_NON_CONFIG_KEYS = frozenset({"name", "description", "modules", "brand"})

_TOKEN = re.compile(r"^\s*(--[A-Za-z0-9_-]+)\s*:\s*([^;]+);", re.MULTILINE)

# Spec 3.1: the 800-token briefing budget, split explicitly. `render_index`
# counts its own output and fails rather than silently exceeding the budget the
# phase's context goal is measured on.
INDEX_TOKEN_BUDGET = 600
INDEX_MAX_PROSE_LINES = 40

# Spec 3.1's routing table, derived from the nine-slice vocabulary. `never` and
# `overrides` are always loaded: both are a few lines, and a prohibition or a
# suppression the chief cannot see has no effect at read time - discovering a
# hard prohibition at stage 5 rather than stage 2 wastes a whole build.
INDEX_ROUTING: dict[str, list[str]] = {
    "always": ["stack", "never", "overrides"],
    "template_or_css": ["ux", "brand"],
    "route_or_query": ["architecture", "security"],
    "new_feature": ["product", "architecture", "conventions"],
    "security_sensitive_path": ["security"],
}

_GENERATED_MARKDOWN = (
    "# GENERATED by `taller resolve` - do not edit. Regenerated, never merged."
)


# --- chain 1 + chain 2 -------------------------------------------------------

def resolve(project_path: Path | str) -> RuleSet:
    """The complete `RuleSet` for a registered project. Pure; writes nothing."""
    project = Path(project_path)
    entry = registry.get_project(project)          # raises ConfigError if unknown
    profile_name = entry["profile"]
    profile = catalogue.read_hub_profile(profile_name)

    missing = catalogue.missing_modules(profile_name)
    if missing:
        raise ConfigError(
            f"Profile {profile_name!r} names modules this hub does not have: "
            f"{', '.join(missing)}. Chain 2 would resolve them into silence, so "
            f"nobody would learn a rule stopped applying. Run `taller setup` or "
            f"restore the module file."
        )

    ruleset: RuleSet = _merge_config(profile, project)
    ruleset["project"] = {
        "path": str(project.resolve()),
        "profile": profile_name,
        "name": entry["name"],
    }
    ruleset["brand"] = _resolve_brand(entry.get("brand"))
    ruleset["slices"] = _resolve_slices(profile, project, ruleset["brand"])
    ruleset["overrides"] = _resolve_overrides(project)
    ruleset["mode"] = "local"
    return ruleset


def _merge_config(profile: dict[str, Any], project: Path) -> RuleSet:
    """Chain 1: hub -> profile -> project, deep merge, later wins (spec 4.4).

    `paths.security_sensitive` and `non_suppressible` append at every level, which
    `config.deep_merge` enforces: a project able to narrow its own security
    surface would make spec 8.2's mandatory gate optional.
    """
    merged = config.load_hub_config()
    profile_config = {
        key: value for key, value in profile.items()
        if key not in PROFILE_NON_CONFIG_KEYS
    }
    merged = config.deep_merge(merged, profile_config)
    merged = config.deep_merge(merged, config.read_project_config(project))

    # A YAML date here would not survive json.dumps in render_snapshot, and the
    # value is informational (spec 5.1: `doctor` warns when it is stale).
    pricing = merged.get("pricing")
    if isinstance(pricing, dict) and isinstance(pricing.get("as_of"), (date, datetime)):
        pricing["as_of"] = pricing["as_of"].isoformat()
    return merged


def _resolve_slices(profile: dict[str, Any], project: Path,
                    brand: dict[str, Any] | None) -> dict[str, ResolvedSlice]:
    """Chain 2: hub modules in profile order, then the project's own file.

    A slice with no sources is **absent** from the result rather than present and
    empty: an absent key says "this project has no product slice", which a caller
    can act on.
    """
    sources: dict[str, list[Path]] = {name: [] for name in SLICE_NAMES}

    for module_id in profile.get("modules", []):
        slice_name = slice_of(module_id)
        if slice_name in PROJECT_ONLY_SLICES:
            continue              # spec 4.3 - ignored, not merged, not preferred
        if slice_name not in sources:
            raise ConfigError(
                f"Module {module_id!r} declares slice {slice_name!r}, which is not "
                f"one of the nine of spec 4.3."
            )
        sources[slice_name].append(paths.modules() / f"{module_id}.md")

    if brand:
        brand_prose = paths.brands() / brand["slug"] / "brand.md"
        if brand_prose.is_file():
            sources["brand"].append(brand_prose)

    for name in SLICE_NAMES:
        project_file = paths.project_constitution(project) / f"{name}.md"
        if project_file.is_file():
            sources[name].append(project_file)

    resolved: dict[str, ResolvedSlice] = {}
    for name in SLICE_NAMES:
        files = [path for path in sources[name] if path.is_file()]
        if not files:
            continue
        resolved[name] = {
            "name": name,
            "sources": [str(path) for path in files],
            "text": _concatenate(files),
        }
    return resolved


def slice_of(module_id: str) -> str:
    """The slice a module provides: its directory, or its own name at the root.

    `never.md` sits at the root of `modules/` because it is the one slice with a
    single file (spec 4.0), so the slice name has to come from somewhere.
    """
    return module_id.split("/")[0]


def _concatenate(files: list[Path]) -> str:
    """Slice text, in application order, LF, one blank line between sources.

    `read_text` normalises CRLF, so a module edited on Windows resolves to the
    same bytes as one edited anywhere else - which spec 4.6 compares.
    """
    chunks = [path.read_text(encoding="utf-8").strip("\n") for path in files]
    return "\n\n".join(chunk for chunk in chunks if chunk) + "\n"


def _resolve_brand(slug: str | None) -> dict[str, Any] | None:
    """`None` when the project's brand is `none` (spec 4.4).

    Values exist only in `brands/<slug>/tokens.css` (spec 4.2), so this is the one
    place they enter the RuleSet. The `--` prefix is kept: it is what the
    constitution gate looks for when it flags the same value used literally.
    """
    if not slug or slug == "none":
        return None
    tokens_path = paths.brands() / slug / "tokens.css"
    if not tokens_path.is_file():
        raise ConfigError(
            f"Brand {slug!r} has no tokens.css at {tokens_path}. Run "
            f"`taller brand new {slug}`, or set the project's brand to none."
        )
    text = tokens_path.read_text(encoding="utf-8")
    return {
        "slug": slug,
        "tokens_path": str(tokens_path),
        "tokens": {name: value.strip() for name, value in _TOKEN.findall(text)},
    }


def _resolve_overrides(project: Path) -> list[dict[str, Any]]:
    """Every override the project records, in file order (spec 4.5).

    The source is repo-relative because it is shown to the owner on a Finding
    (spec 7.4), and because an absolute path would differ per machine.
    """
    path = paths.project_constitution(project) / "overrides.md"
    if not path.is_file():
        return []
    relative = path.relative_to(Path(project)).as_posix()
    return overrides.parse(path.read_text(encoding="utf-8"), source=relative)


# --- the generated artefacts (spec 4.6, 3.1, 4.2.1) --------------------------
#
# All three are RuleSet -> bytes, pure, and byte-stable across two calls: the
# tamper check compares the committed file against an in-memory re-render, so an
# unstable renderer would report a clean repository as modified. That means
# sorted keys, a fixed indent, LF, and an explicit trailing newline - never a
# dict's insertion order and never os.linesep.

def render_snapshot(ruleset: RuleSet) -> bytes:
    """`.taller/resolved.json` — the whole RuleSet, slice text included.

    CI cannot see the hub (spec 4.6), so the text travels rather than the paths.
    `mode` is written as `"local"` whatever the given ruleset says, so that a
    snapshot re-rendered from a loaded one is byte-identical to the original; it
    is `load_snapshot` that labels a run `"ci"`.
    """
    payload = {**ruleset, "mode": "local"}
    text = json.dumps(payload, sort_keys=True, indent=2, ensure_ascii=False,
                      default=_json_scalar)
    return (text + "\n").encode("utf-8")


def load_snapshot(path: Path | str) -> RuleSet:
    """The committed snapshot, as the RuleSet a CI gate runs against.

    Accepts a project root or the snapshot file itself. `mode` is `"ci"`: the one
    behavioural difference between a local and a CI gate run (spec 4.6), carried
    inside the RuleSet so `gates/*.py` stay pure over their arguments.
    """
    given = Path(path)
    snapshot = given if given.is_file() else paths.project_snapshot(given)
    try:
        data = json.loads(snapshot.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ConfigError(
            f"{snapshot} does not exist. Run `taller resolve` and commit it."
        ) from exc
    except json.JSONDecodeError as exc:
        raise ConfigError(f"{snapshot} is not valid JSON: {exc}") from exc
    if not isinstance(data, dict) or "slices" not in data:
        raise ConfigError(f"{snapshot} is not a resolved snapshot.")

    # JSON has no date. `overrides.apply` compares `until` against today, so a
    # string here would raise inside the gate rather than at load time.
    for override in data.get("overrides") or []:
        if override.get("until"):
            override["until"] = date.fromisoformat(str(override["until"]))

    data["mode"] = "ci"
    return data


def render_index(ruleset: RuleSet) -> bytes:
    """`.taller/constitution/00-index.md` — the routing map the chief parses.

    Spec 3.1: YAML front matter holding the routing table, then one line per
    provided slice, carrying that slice's own first `> ` summary. No model call,
    and it counts its own output: over budget is an error, never a silent
    overrun of the goal the phase is measured on.
    """
    project = ruleset["project"]
    front = {
        "project": project["name"],
        "profile": project["profile"],
        "brand": (ruleset["brand"] or {}).get("slug"),
        "provided": [name for name in SLICE_NAMES if name in ruleset["slices"]],
        "routing": {key: list(value) for key, value in INDEX_ROUTING.items()},
        "security_sensitive": list(ruleset["paths"].get("security_sensitive", [])),
    }

    lines = [
        "---",
        _GENERATED_MARKDOWN,
        yaml.safe_dump(front, sort_keys=False, default_flow_style=False,
                       allow_unicode=True, width=10_000).rstrip("\n"),
        "---",
        "",
        f"# {project['name']} - what to load, and when",
        "",
        "A routing map, not a briefing: load a slice by need, per the table above.",
        "`never` and `overrides` load on every ticket, at stage 2.",
        "",
    ]
    for name in SLICE_NAMES:
        resolved = ruleset["slices"].get(name)
        if resolved is None:
            continue
        summary = _summary_of(resolved["text"])
        lines.append(f"- **{name}**: {summary}" if summary else f"- **{name}**")

    text = "\n".join(lines) + "\n"
    estimate = estimate_tokens(text)
    if estimate > INDEX_TOKEN_BUDGET:
        raise ConfigError(
            f"00-index.md is about {estimate} tokens, over its {INDEX_TOKEN_BUDGET}-token "
            f"budget (spec 3.1). Shorten a module's `> ` summary line, or trim "
            f"`paths.security_sensitive`."
        )
    prose = lines[lines.index("---", 1) + 1:]
    if len([line for line in prose if line.strip()]) > INDEX_MAX_PROSE_LINES:
        raise ConfigError(
            f"00-index.md prose is over {INDEX_MAX_PROSE_LINES} lines (spec 3.1)."
        )
    return text.encode("utf-8")


def render_tokens(ruleset: RuleSet) -> bytes | None:
    """`<project>/<paths.brand_tokens>` — the brand's tokens.css, verbatim.

    The hub is outside every project repository and outside the Docker image, so
    the hub file cannot be the one the browser loads (spec 4.2.1). `None` when the
    project has no brand, and also when the profile sets no `brand_tokens` path:
    in both cases there is nothing to write.

    The header names the brand by slug and never by path. An absolute hub path
    would be machine-specific, and this file is committed and then compared byte
    for byte on whatever machine checks the repository out.
    """
    brand = ruleset["brand"]
    if not brand or not ruleset["paths"].get("brand_tokens"):
        return None
    header = (
        f"/* GENERATED by `taller resolve` from the hub brand `{brand['slug']}`.\n"
        f"   Do not edit: the values live in the brand, and this copy is rewritten\n"
        f"   and never merged (spec 4.2.1). */\n"
    )
    verbatim = Path(brand["tokens_path"]).read_text(encoding="utf-8")
    return (header + verbatim).encode("utf-8")


def estimate_tokens(text: str) -> int:
    """An approximation: `ceil(len(text) / 3.5)`.

    There is no local tokenizer and a real count costs an API call, so this is
    deliberately pessimistic - it over-counts English prose, which means passing a
    budget check makes the true count almost certainly lower. It is not a
    measurement and must not be reported as one.
    """
    return math.ceil(len(text) / 3.5)


def _summary_of(text: str) -> str | None:
    """Every `> ` summary the slice's sources carry, in profile order (spec 3.1).

    Not just the first. A slice can be several modules - `conventions` is
    `conventions/python` then `conventions/js` for flask-sqlite - and taking only
    the first would have silently dropped the JavaScript conventions from the one
    file the chief reads on every session. Spec 3.1 says "concatenated in profile
    order", and the widest index measures well under its budget, so there is room
    to honour that.

    A source with no summary contributes nothing: `overrides.md` opens with front
    matter, and a project's own `product.md` may not carry one.
    """
    summaries = [
        line[2:].strip()
        for line in text.splitlines()
        if line.startswith("> ") and line[2:].strip()
    ]
    return " ".join(summaries) or None


def _json_scalar(value: Any) -> str:
    """Dates reach JSON as ISO strings; anything else is a bug worth raising."""
    if isinstance(value, (date, datetime)):
        return value.isoformat()
    raise TypeError(
        f"{type(value).__name__} cannot be written to a snapshot: a RuleSet holds "
        f"only JSON scalars, lists and dicts (spec 4.4)."
    )
